### ISSUE TITLE
AppleSkin support

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/VampirismIntegrations#1]
@macks2008
> Apple skin, when installed, will normally show you an overlay on your hunger bar indicating your saturation and exhaustion, along with showing the exact numbers in the F3 debug screen. For obvious reasons, this doesn't work so well for vampires. The debug menu shows hunger 10, sat 5, and 0 exhaustion,, regardless of what I'm doing. I don't mind the overlay not working, as your "blood bar" would have to be reworked to display the information the hunger bar normally displays with apple skin installed, but could you at least synchronize vanilla's hunger information with your blood bar if possible?

Maybe it is sufficient to display blood and saturation in Vampirism and let AppleSkin handle exhaustion which would not require implementing a sync.

**Comment by Lukebb04** [comment]
Just wondering will the overlay still get fixed?
