### ISSUE TITLE
ToroQuest integration

### ISSUE THREAD

**Issue by Rutes** [TeamLapen/VampirismIntegrations#10]
Would be nice to see the guards and sentries from the mod ToroQuest kill vampires near the villages. Or maybe run away from them and let the vampire hunters deal with them instead.
https://github.com/ToroCraft/ToroQuest

**Comment by maxanier** [comment]
I am not sure if I will be able to make the guards/sentries attack the vampires, but I can definitely make the vampires run away

**Comment by maxanier** [comment]
Ok, guards and sentries now attack vampires.
Might break with future ToroQuest updates, but should be rather stable.

I guess there are opportunious for a deeper / feature rich integration, but I think the user base playing both mods together is quite small

**Comment by Rutes** [comment]
sweet, thanks! well maybe the player base will increase a little with my modpack 👍

**Comment by PendragonII** [comment]
In future updates where Vampires controls the village, perhaps the village should put it's alliance with the Vampires (and not the Village Lord) or similar. But sentries should not kill Vampires; it would be neat to see sentries become Vampires themselves (when the update allowing Vampires to capture villages)

**Comment by maxanier** [comment]
Have to come back to this once the village rework is complete

/remind me about this in two weeks
