### ISSUE TITLE
Request compat for:Cold Sweat

### ISSUE THREAD

**Issue by FLNCT0293** [TeamLapen/VampirismIntegrations#100]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge): https://www.curseforge.com/minecraft/mc-mods/cold-sweat

Link to mod source/API: 

## What should be integrated exactly

Vampires should not suffer cold as harsh as human players
## Additional comments

If possible make it for 1.19.2

**Comment by Cheaterpaul** [comment]
included in 1.20.1-1.8.0
