### ISSUE TITLE
reconizing issue 1.12.2

### ISSUE THREAD

**Issue by Nathan22211** [TeamLapen/VampirismIntegrations#11]
when you have this installed and your using the latest version of the vampirism mod. it doesn't recognize the mod as the right version. even if it says the 1.12.2 alpha and above is supported

**Comment by maxanier** [comment]
Do you have the latest version of this installed? 0.1.0-alpha+01-07-22-19

**Comment by Nathan22211** [comment]
yes I do

**Comment by Nathan22211** [comment]
I'm using win 10 but the operating system is not up to date from what it seems

**Comment by Nathan22211** [comment]
ok I found the issue. you have the useDependencyInformation": set to false it has to be true.

**Comment by maxanier** [comment]
Unfortunately, I cannot reproduce this issue using the latest versions. But I am using Linux and MultiMC so that might be way.

useDepdencyInformation in the mcmod.info should not be required, it isn't enabled in Vampirism either.

If the issue persists please upload the fml-client-latest.log here

**Comment by Nathan22211** [comment]
ok here's the latest log

https://pastebin.com/YxFAu4p1

**Comment by maxanier** [comment]
The integrations mod requires Vampirism-**1.4.0**-alpha+01-07-19-32 to be installed.
You have only Vampirism 1.3.7 installed. The versioning scheme works from the left to the right
Even if 1.3.7 was released later, it is still 1.3, but with some more bugfixes, whereas the latest alphas are 1.4 with new features

https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files?filter-status=1&filter-game-version=2020709689%3A6756
