### ISSUE TITLE
Tough as nails

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/VampirismIntegrations#15]
https://minecraft.curseforge.com/projects/tough-as-nails?gameCategorySlug=mc-mods&projectID=246391

Vampires shouldn't need to drink water to refill the "thirst meter". Perhaps Vampires should be slightly more resistant to temperature changes than mortals - @MLMII

**Comment by Rutes** [comment]
This might be a delicate thing to tweak/balance. TAN does intentionally add a lot of difficulty to a pack/server. Having Vampirism shouldn't nullify everything, but I agree that water-thirst doesn't make sense for a vampire. Since vampires are "undead" it seems reasonable that cold would not affect them as much. If anything it would help to prevent decay, right? Heat/cold protection could be something to build into the Vamp armors, though I think that can already be done with TAN config.

**Comment by maxanier** [comment]
UtsuroTsukasa
> Integration idea: if tough as nails is loaded the campfires from that mod will replace the vampirism campfires in camps. Also, when you turn into a vampire, thirst and temperature are ignored.

**Comment by maxanier** [comment]
by @Rufflikerex

> -Completely disable thirst for vampires.
-Make vampires completely immune to cold temperatures.
-Make vampires more susceptible to warmer temperatures using debuffs. This would force vampires to prioritize pvp attacks during winter (Serene Seasons), and during nights.
-Make sunscreen only block the sun's direct effects (sunscreen doesn't block temperature debuffs and vampires can still burn in temperatures that would normally burn normal players, but damage directly from the sun would still be blocked).
-Make vampires reach the "burning temperature" much sooner on the heat spectrum than other players.

**Comment by maxanier** [comment]
So I had a look at their code/api and here are a couple of possibilities:

***Thirst***
1) Keep the thirst meter at 20 at all times
2) Ensure thirst meter never drops below 1, so no damage is inflicted

In addition I could probably tint the thirst meter overlay violet to indicate that vampires are not affected

***Temperature***
1) Remove damage of hypothermia potion and increase damage of hyperthermia potion
2) Have a permanent positive temperature offset for vampires


***Camp Fire***
- Generate hunter camps with TAN campfire instead of Vampirism one


@Rutes @Rufflikerex what do you think?

**Comment by Rutes** [comment]
I like it!
I'll put this in another thread, but if you're able to replace the campfire generation, might there also be the potential to replace the tents at camps with those from the Camping Mod by Rikmuld?

**Comment by maxanier** [comment]
Probably not since the tents are used as spawners for the hunters.

Do you prefer option 1) or 2) respectively?

**Comment by Rutes** [comment]
Option 2 and 1: Thirst meter never below 1, but I would say make blood sate the thirst meter as well as the normal hunger/blood meter. For the other, the potion effects would be the more noticeable/effective change.
Found this stack exchange post which might be interesting to review:
https://scifi.stackexchange.com/questions/8962/what-bodily-functions-work-in-vampires

**Comment by maxanier** [comment]
The feature is basically implemented, but due to an issue with TAN I currently cannot test it. Let's see if I will get an answer to the issue I have created

**Comment by maxanier** [comment]
So, they fixed the issue, so I can finally test the changes. Looking good so far.
Still have to actually replace the campfire, but that requires a Vampirism update.

**Comment by Rufflikerex** [comment]
Sorry for the long delay, I have forgotten about this thread. I love the proposed features, and this feature will allow your mod to fit in with my modpack without conflicts.

**Comment by maxanier** [comment]
In 1.12 this should be working
For 1.14 TAN has been discontinued

**Comment by LisYan20** [comment]
Hello, have you already done it or what? On what versions is this available? Is there a separate command to disable thirst? Or what? I'm just playing on tlauncher 1.18.2 mod vampirizm and thirst, temperature, werewolf

**Comment by LisYan20** [comment]
Бегать невозможно когда обычная жажда для воды и крови полная, бегать невозможно, надо пить воду, хотя вампиры не пьют воду, даже если пьют, это тоже жидкость и эта жидкость вода не восполняет жажду.

**Comment by LisYan20** [comment]
It is impossible to run when the usual thirst for water is not replenished, and the blood is full, it is impossible to run, you need to drink water, although vampires do not drink water, even if they drink, it is also a liquid and this liquid water does not replenish thirst, should not be replenished in minecraft.

**Comment by LisYan20** [comment]
Кстати было бы прикольно, мод оборотня связана с модом вампиризма. В обличье оборотня, волка то днём горит присолнце. Потому что у него шерсть, а ночью холодно, особенно в холодных биомах, там холод не действует. В облике человека как обычно у игроков. С жаждой думаю не надо убирать, но за то не может отравится от обычной воды и чистой в любом облике, а от грязной ещё как может.

**Comment by LisYan20** [comment]
By the way, it would be cool, the werewolf mod is currently connected with the vampirism mod. In werewolf form, the wolf burns in the sun during the day. Because it has fur, and at night it is cold, especially in cold biomes, where the cold does not work. In human form, as usual for players, the temperature works. I think there is no need to remove thirst, but it cannot be poisoned by ordinary water and clean water in any form of the image in which it is, but it can be poisoned by dirty water.

**Comment by LisYan20** [comment]
People, where is the reaction? I've been waiting for two weeks, I don't know how long, if you're busy you'd write at least something. Let's say I can't, I'm busy or lazy, I have more important things to do, or I don't want to sort it out. At least something, damn.
