### ISSUE TITLE
Level up lag

### ISSUE THREAD

**Issue by Ceifeire** [TeamLapen/VampirismIntegrations#21]
## Versions
- Minecraft: 1.12.2                    
- Forge: FTB Revelations                       
- Vampirism:1.4.0                  
- VampirismIntegrations:1.0.0                            

## Issue Description
Whenever leveling up everyone player within a few chunks gets frozen by lag for up to 5 mins so far. since level 5.

## Reproduce Steps
level up vampire

## Additional Information
not crashing but very bad lag

**Comment by maxanier** [comment]
Wow, that is an insanely overloaded modpack ^^

But I can confirm the issue. Seems to be somehow related to the animations (probably the particles) involved in the ritual.
However, this can be reproduced without VampirismIntegrations -> moving to Vampirism
/move to main
