### ISSUE TITLE
(Suggestion) Tough as Nails integration idea

### ISSUE THREAD

**Issue by Rufflikerex** [TeamLapen/VampirismIntegrations#23]
Tough as Nails adds body temperature and thirst to Minecraft. I would love to see a vampirism integration update with the following additions:

-Completely disable thirst for vampires.
-Make vampires completely immune to cold temperatures.
-Make vampires more susceptible to warmer temperatures using debuffs. This would force vampires to prioritize pvp attacks during winter (Serene Seasons), and during nights.
-Make sunscreen only block the sun's direct effects (sunscreen doesn't block temperature debuffs and vampires can still burn in temperatures that would normally burn normal players, but damage directly from the sun would still be blocked).
-Make vampires reach the "burning temperature" much sooner on the heat spectrum than other players.

These are just a few ideas, please develop this mod as you see fit.
Thanks for reading!

Edit:
Small idea, but HarvestCraft's version of garlic could also be implemented.

**Comment by Rutes** [comment]
https://github.com/TeamLapen/VampirismIntegrations/issues/15

**Comment by maxanier** [comment]
Closing this as duplicate.
See #15 for discussion
