### ISSUE TITLE
Millenaire Integration

### ISSUE THREAD

**Issue by FiddleSticks96** [TeamLapen/VampirismIntegrations#26]
Is there any chance of adding Millenaire to the integration? Millenaire adds dynamically growing villages of various cultures as well as its own NPCs. These villages can grow quite large and you can have a hand in helping them or destroying them. It would be cool to be able to infiltrate one of these villages as a vampire and slowly take over or to protect said village from vampires from invading.

**Comment by qamarkarasu** [comment]
It would be great if any integration find a way in this mod. At the moment these villages are useless for Vampires. But Millenaire is max on MC 1.12.2, vampirism is on 1.16.

**Comment by maxanier** [comment]
Exactly, only 1.16 (or whatever the latest Vampirism version is on) is considered.
Please reopen/recreate if Millenaire should ever be updated. Also, please be as specific as possible about what should be added then.
