### ISSUE TITLE
Howling Moon

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/VampirismIntegrations#3]
If Howling Moon should be updated at any point and I receive some answer here: 
https://github.com/Razmen/HowlingMoon/issues/4

**Comment by Rutes** [comment]
Howling moon has been updated for 1.12
https://minecraft.curseforge.com/projects/howling-moon

I have a few of my server players testing it out in single player alongside Vampirism to check for any conflicts or weirdness

**Comment by Rutes** [comment]
A good integration here might be for the vampire hunters to also hunt/attack werewolves. And vice-versa, for the "werewolf hunters" to also attack vampires.
