### ISSUE TITLE
Integration with Ancient Warfares 2

### ISSUE THREAD

**Issue by sfaruque6** [TeamLapen/VampirismIntegrations#34]
Since there are vampires in the Ancient Warfares mod as well, I figured that there could be a few things that can be added. I might update this later.

-Vampires from Vampirism can spawn in the vampire-based structures from Ancient Warfares
-The structures from Ancient Warfares can also spawn in the Vampire Forest biome
-Vampires from AW can pass the sanguarine effect to players

Note that Vampire Hunters already attack the Vampires from AW, albeit at a disadvantage due to the fact that they hit hard

**Comment by maxanier** [comment]
Still waiting for AW2 to be updated to 1.16

**Comment by Cheaterpaul** [comment]
Ancient Warfares 2 did not update past 1.12

This issue can be reopened when the mod updates
