### ISSUE TITLE
[1.16.4] BloodMagic blood not converting

### ISSUE THREAD

**Issue by lanAnderson** [TeamLapen/VampirismIntegrations#35]
## Versions
- Minecraft:  1.16.4                 
- Forge:  35.1.4                     
- Vampirism-1.16.4-1.7.0-alpha+20201126-0937                
- VampirismIntegrations-1.16.4-1.4.0-beta.2                      

## Issue Description
Sieve does not convert Blood Magic blood. Using BloodMagic-1.16.3-3.0.1-6

Tried a tank on top as well as pumping Blood Magic blood on top (w/ a blood tank on bottom for output)

## Additional Information
N/A

**Comment by maxanier** [comment]
I was not aware that Blood Magic is now available for 1.16.

Will readd the integration

**Comment by lanAnderson** [comment]
I appreciate it

**Comment by maxanier** [comment]
Should be working in latest release
