### ISSUE TITLE
Server crashes on startup, HWYLA involved

### ISSUE THREAD

**Issue by ayeh6** [TeamLapen/VampirismIntegrations#37]
## Versions
- Minecraft: 1.16.4                   
- Forge: 35.1.28                       
- Vampirism: 1.7.1                 
- VampirismIntegrations: 1.4.0                          

## Issue Description
Server crashes when starting up, looking at the crash report it involves HWYLA 1.10.11-B78 and vampirism integrations

## Reproduce Steps
Starting a server with the mods I have on the minecraft, forge and mod versions I listed

## Additional Information
Crash report: https://pastebin.com/sgsMBnWc

**Comment by Rutes** [comment]
Hwyla is a client-side mod - just remove it from your server.

**Comment by maxanier** [comment]
I could not reproduce it and with just Vampirism.
Added a fix/workaround for anyway. Please update
