### ISSUE TITLE
Notification inside Vampirism

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/VampirismIntegrations#4]
Notify admin users if a mod with available integration is present but this mod is not installed

**Comment by macks2008** [comment]
make sure whatever you're using to detect "admin users" doesn't return false for players that have cheats disabled in single player. I vaguely remember having issues with that before, where something besides commands depended on the allowCommands tag

**Comment by maxanier** [comment]
good point, guess I will use isSingleplayer || isAdmin. I think I am using something similar for the update notifications already
