### ISSUE TITLE
[Feature] Lightweight blood mechanics compat

### ISSUE THREAD

**Issue by Carvercarver1** [TeamLapen/VampirismIntegrations#41]
## What would you like to have changed or added to Vampirism
https://www.curseforge.com/minecraft/mc-mods/lightweight-blood-mechanics 
Cross-compat with this mod, e.g vampires will not bleed, and the blood meter will also sync between the two? Probably would require cooperation with the mod author.

## Does this make the mod experience more balanced?
Yes.

**Comment by maxanier** [comment]
Only available for 1.12 atm, so we will have to wait until it is updated to latest MC version

**Comment by Cheaterpaul** [comment]
Lightweight Blood Mechanics is still only available for Minecraft 1.12

This issue can be reopened when the mod updates
