### ISSUE TITLE
Extend compat for: Evilcraft 1.16

### ISSUE THREAD

**Issue by toErIpNid** [TeamLapen/VampirismIntegrations#44]
I suggest extending/improving the already implemented integrations for the mod mentioned in the title.

## What should be added/changed exactly
 
 
Maybe add some vampirism recipes to blood infusers and add the ability to drink blood from extractors. 

## Additional comments

**Comment by ZainChen** [comment]
Very much needed

**Comment by maxanier** [comment]
"add some vampirism recipes to blood infusers" is very vague

**Comment by ZainChen** [comment]
> "add some vampirism recipes to blood infusers" is very vague

Evilcraft filters blood to be drinkable by vampires. I really like this feature and hope that 1.16 will support it.( •̀ ω •́ )✧

**Comment by ZainChen** [comment]
> > "add some vampirism recipes to blood infusers" is very vague
> 
> Evilcraft filters blood to be drinkable by vampires. I really like this feature and hope that 1.16 will support it.( •̀ ω •́ )✧

Very thankful "Add conversion factor for Evilcraft blood."

I'm already using it, as a vampire, I am no longer hungry, hahahaha !!!!

**Comment by ZainChen** [comment]
Here, 1.16 can be added. Evilcraft (1.12, 1.16)
![image](https://user-images.githubusercontent.com/15615524/123442353-60ad0900-d607-11eb-8b83-9f2bc1179a16.png)
