### ISSUE TITLE
Request compat for: Minecraft Comes Alive 5.3.1 version (1.12.2)

### ISSUE THREAD

**Issue by sfaruque6** [TeamLapen/VampirismIntegrations#45]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):

Link to mod source/API: 

## What should be integrated exactly
I'm pretty sure Vampirism for 1.12.2 is already discontinued, but just in case, the newest version of Minecraft Comes Alive 1.12.2 has several bugs and is officially discontinued as of now. There should be a version to integrate with the 5.3.1 version, the latest actual-working MCA version. Everything else will remain the same.

**Comment by sfaruque6** [comment]
Edit: just forget this suggestion; I don't think it will apply

**Comment by maxanier** [comment]
There should already be MCA support on 1.12. Also, yes Vampirism 1.12 is discontinued
