### ISSUE TITLE
Survive Mod for 1.16.5 

### ISSUE THREAD

**Issue by ThatCrazyDad** [TeamLapen/VampirismIntegrations#46]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge): https://www.curseforge.com/minecraft/mc-mods/survive

Link to mod source/API: https://github.com/Stereowalker/Survive

## What should be integrated exactly
 Remove water and stamina component and increase need for blood when vampire.  No change for hunter concerning the Survive mod.  Allow for  tiredness as vampire. Possibly increased damage from heat as vampire and  no damage from cold.  As realistic as I could think.

## I can help with
I can help test builds.

## Additional comments
 Obviously I am in no rush to see this happen and to be quite honest I would be super excited to help test in any way I can.  I prefer the Survive mod over Tough as Nails mainly because of its simplicity.  Thank you again for your time.

**Comment by maxanier** [comment]
You can give https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations/files/3388996 a try.
It removes thirst, increases cold resistance and decreases heat resistance. It also increases a vampires energy, but does not complete remove this mechanic. Unfortunately, the energy bar is not rendered while being a vampire. I think that has to be changed on Survive's end though.
