### ISSUE TITLE
Request compat for: Diet

### ISSUE THREAD

**Issue by yavincl** [TeamLapen/VampirismIntegrations#48]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):
https://www.curseforge.com/minecraft/mc-mods/diet
Link to mod source/API: 
https://github.com/TheIllusiveC4/Diet

## What should be integrated exactly
If Diet, on 1.16.5, is installed, Vampire players should have their diet privileges revoked, erm, just make it so the Diet mod doesn't buff, appear, and have a button for them to look at current nutrition. I don't know whether to post this as an issue here or on Diet's page, so I'm posting it on both.

## I can help with
Testing

**Comment by yavincl** [comment]
https://github.com/TheIllusiveC4/Diet/issues/59#issuecomment-864502614

**Comment by maxanier** [comment]
You can give https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations/files/3388996 a try. It disables diet for vampires. It requires Vampirism 1.8.0-beta.3 though.
