### ISSUE TITLE
Request compat for:  Guard Villager

### ISSUE THREAD

**Issue by Tuff00** [TeamLapen/VampirismIntegrations#50]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):
https://www.curseforge.com/minecraft/mc-mods/guard-villagers/files

Link to mod source/API: 
https://github.com/seymourimadeit/guardvillagers

## What should be integrated exactly

Is it possible to make the guards join one of the 2 factions. (or stay neutral) but defend the villages  that they belong to from raids and rogue vampires  for example . Including defending neutral villages?

## I can help with

I can help play test the builds if you need me to.

**Comment by Cheaterpaul** [comment]
Included in 1.20.1-1.8.0
