### ISSUE TITLE
Request compat for:Tough as nails 1.16.5

### ISSUE THREAD

**Issue by Enikimm** [TeamLapen/VampirismIntegrations#55]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge): https://www.curseforge.com/minecraft/mc-mods/tough-as-nails

Link to mod source/API: https://github.com/Glitchfiend/ToughAsNails

## What should be integrated exactly
 make it so it shows the temperature of the vampiric player raises dramatically to burning hot during the sun.  or for players who have godly vampire show it less intensely.

## Additional comments
 Not sure if I understand this format but I'm guessing I input stuff correctly..    anyways this is the mod version of tough as nails I'd like compatible.

**Comment by maxanier** [comment]
a) There is already compatibility with TAN (vampires do not have to drink water)
b) You did not clarify what exactly should be changed by Vampirism Integrations compat
