### ISSUE TITLE
Request compat for: Minecraft Comes Alive Reborn (1.16) 

### ISSUE THREAD

**Issue by ElRoque** [TeamLapen/VampirismIntegrations#59]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):

Link to mod source/API:

**Comment by ElRoque** [comment]
I would like to see integrations added for the mod mentioned in the title.
It's only in 1.16

curseforge: https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-testing

I don't know why, MCA villagers become vanilla villagers.

**Comment by JasonPra** [comment]
Yesss! I really miss this from 1.12.2 It would be great to be able to turn MCA Reborn villagers but not just into vampires though now but werewolf's to. 
**If there is anything I can do to help just reach out. You can reach me at jasonmp1993@gmail.com**

I went and found the source code for MCA Reborn in hopes of being helpful.
https://github.com/Luke100000/minecraft-comes-alive

**Comment by maxanier** [comment]
It is supported for MC 1.18. I don't know if we find the time to back port this to 1.16

**Comment by tallubhai** [comment]
I too would love to see an integration with MCA Reborn on 1.16. Please, if you can find the time for it, make it happen!
