### ISSUE TITLE
Request compat for: Tough As Nails

### ISSUE THREAD

**Issue by MaxWasUnavailable** [TeamLapen/VampirismIntegrations#69]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):

https://www.curseforge.com/minecraft/mc-mods/tough-as-nails

Link to mod source/API: 

https://github.com/Glitchfiend/ToughAsNails

## What should be integrated exactly

- No thirst for vampires. (Possibly keep it full at all times / hide it?)
- No cold damage for vampires, or significantly reduced temperature floor for damage?
- Increased heat damage, perhaps?
- Hunter campfires that work with TaN.

## I can help with

Testing, both singleplayer and on a dedicated server with a fair amount of players.

## Additional comments

I noticed there was a past integration, but it doesn't appear to be functional in the current version?

https://github.com/TeamLapen/VampirismIntegrations/issues/15

**Comment by maxanier** [comment]
Was already added some time ago, forgot to close this
