### ISSUE TITLE
Request compat for: Comes Alive 1.18.1 forge

### ISSUE THREAD

**Issue by dylan-jara** [TeamLapen/VampirismIntegrations#72]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge): https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn

Link to mod source/API: I don't know what to put here?

## What should be integrated exactly

add compatibility with mca reborn villagers, for vampirism

**Comment by maxanier** [comment]
This is already the implemented in the 1.18.2 versions of integrations
