### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by ghost** [TeamLapen/VampirismIntegrations#73]
## Versions
- Minecraft:                    1.18.2
- Forge:                       4.0.1.73
- Vampirism:Vampirism-1.18.2-1.8.5
- Integrations:VampirismIntegrations-1.18.2-1.7.0-alpha+20220703-0014

## Issue Description
![image](https://user-images.githubusercontent.com/83486178/185734558-cfd17d3d-7df0-4829-bd8c-844fe7732006.png)

## Additional Information
[latest.log](https://github.com/TeamLapen/VampirismIntegrations/files/9386449/latest.log)
[crash-2022-08-20_15.35.31-fml.txt](https://github.com/TeamLapen/VampirismIntegrations/files/9386450/crash-2022-08-20_15.35.31-fml.txt)

**Comment by Cheaterpaul** [comment]
The MCA Reborn devs destroyed the compatibility. For the time being please use MCA Reborn 7.3.17
