### ISSUE TITLE
Request compat for: First Aid

### ISSUE THREAD

**Issue by huskago** [TeamLapen/VampirismIntegrations#74]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):
https://www.curseforge.com/minecraft/mc-mods/first-aid

Link to mod source/API: 
https://github.com/ichttt/FirstAid

## What should be integrated exactly

When we are in the sun, we take the damage

**Comment by maxanier** [comment]
Hello, thank you for your request.
Can you please extend on the exact integrations.
What is the current behavior when a vampire player moves into sun light and what should be the changed behavior?

**Comment by huskago** [comment]
I'm playing in 1.12.2, so the problem is that when I'm a level 1 vampire, I don't take fire damage from the sun, but I have the yellow effect that warns me that I'm under the sun and that I have to take damage, but on the other hand, when I increase my level, I start taking damage.
So I find it quite strange, because I have tough as nail, but the temperature does not increase. 
Also in the skills that you can have, you can turn into a bat, but when you turn into that, you die for no reason, and I think because your life decreases.

That's all I can think of right now, and I would like to know if you could fix this problem if possible.

**Comment by maxanier** [comment]
I do not see any relation to FirstAid here.
The sun damage behavior is correct. You only start taking damage on higher levels.
The bat mode death is a bug, that may or may not be related to FirstAid. There have been similar reports about this that are resolved in newer MC versions.
