### ISSUE TITLE
Bug - New Main Mod Update Breaks MCA Reborn Compat

### ISSUE THREAD

**Issue by whiteglovian** [TeamLapen/VampirismIntegrations#77]
## Versions
- Minecraft: 1.16.5                  
- Forge: 36.2.39                      
- Vampirism: 1.9.0-alpha
- Integrations: 1.6.1

I am unable to infect Minecraft Comes Alive Reborn villagers with Sanguinaire, I don't know if it's user error, but I've tried just about every angle while crouching. I used both my hotkey and the selection wheel, I crouched from behind and aimed for the square of the back more often than not. While I can suck blood, they never transform into vampires. However, I can infect cows, sheep, pigs, rabbits, horses, etc.

## Reproduce Steps
1. Get the infect/bats power
2. Crouch + infect hotkey (my hotkey is 1, I moved the tool select to the numpad so there wasn't a conflict. So, my key combo would be 1 + ctrl)

## Additional Information
N/A

**Comment by maxanier** [comment]
The MCA Reborn is currently not supported in MC 1.16 (#59). Only for 1.18.
