### ISSUE TITLE
Request compat for: Better Combat

### ISSUE THREAD

**Issue by sssHpion007** [TeamLapen/VampirismIntegrations#79]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus

Link to mod source/API: https://github.com/ZsoltMolnarrr/BetterCombat

## What should be integrated exactly
Weapon compatibility with this mod. Axes work without compatibility, but swords don't. I would like to have compatibility so as not to dig into the config.

## I can help with
It is unlikely that it will be needed

**Comment by Cheaterpaul** [comment]
it is already implemented and will be available with the next version

https://github.com/TeamLapen/VampirismIntegrations/pull/78
