### ISSUE TITLE
Biomes O' Plenty visceral heap blood doesn't convert

### ISSUE THREAD

**Issue by JetyWawoo** [TeamLapen/VampirismIntegrations#80]
## Versions
- Minecraft: 1.19.2
- Forge: 43.1.52
- Vampirism: 1.9.0-beta.3
- Integrations: 1.8.0-alpha+20221105-1524

## Issue Description
Biomes O' Plenty blood from the visceral heap biome is not converted even though in the config it's set and should be converted. You can't drink it, put it in a blood container, blood sieve, or blood grinder. Same with any of the other visceral heap blocks and items, you can't grind them into blood either.

## Reproduce Steps
1. Try to drink or convert the blood and blood bucket from Biomes O' Plenty.

## Additional Information
None.

**Comment by maxanier** [comment]
Thank you. Will be fixed with next version
