### ISSUE TITLE
Request compat for: player companion

### ISSUE THREAD

**Issue by BlackDarte** [TeamLapen/VampirismIntegrations#86]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):https://www.curseforge.com/minecraft/mc-mods/player-companions

Link to mod source/API: https://github.com/MarkusBordihn/BOs-Player-Companions/blob/main/README.md

## What should be integrated exactly
Players companions enter in a death loop when there blood is suck by player/npc to death the problem is the same for evry companions of the mods( you can right click if you but if done they die)

**Comment by maxanier** [comment]
The now available beta for 1.19.3 will replenish the companions blood on respawn/death.
