### ISSUE TITLE
Request compat for: Supernatural and Graveyard Biomes

### ISSUE THREAD

**Issue by Atlantispy** [TeamLapen/VampirismIntegrations#87]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):https://www.curseforge.com/minecraft/mc-mods/supernatural
https://www.curseforge.com/minecraft/mc-mods/the-graveyard-biomes-forge

Link to mod source/API: 
https://github.com/Jusey1/supernatural
Graveyard Biomes doesn't have open github but should just be able to add their ID I assume?

## What should be integrated exactly

Vampirism should be equivalent across Supernatural and Vampirism, balancing the bonuses and drawbacks.
Graveyard Biomes should not cause sunlight damage.

## I can help with

Can provide IDs for the biomes if you need.
Can test compatibility.

**Comment by maxanier** [comment]
I have added the haunted biomes to the exclusion list. The normal graveyard forest is not included by default. I think it does not make too much sense as there is no fog/darkness. But there are large trees, so you don't get much sun damage anyways. I have still added a config option to manual exclude that biome too.

Regarding supernatural: As they add their own interpretation of vampires, integration between the two mods is not really viable in my opinion. Also they don't have an API.
