### ISSUE TITLE
Advanced Rocketry

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/VampirismIntegrations#9]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge): https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry

Link to mod source/API: https://github.com/zmaster587/AdvancedRocketry/tree/master/src/main/java/zmaster587/advancedRocketry/api

## What should be integrated exactly

Make sure vampire players (and NPCs) do not suffocate in no atmosphere space

**Comment by Ceifeire** [comment]
Do you have a planned time when we could expect to see this?

**Comment by maxanier** [comment]
No

**Comment by Cheaterpaul** [comment]
Advanced Rocketry is not available for Minecraft 1.20

This issue can be reopened when the mod updates
