### ISSUE TITLE
Request compat for:EPIC FIGHT Compat would be awesome!  When changing to werewolf, bat and others in epic fight mode the model gets all messed up.

### ISSUE THREAD

**Issue by CaliberMC** [TeamLapen/VampirismIntegrations#94]
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing.

## About the mod
Link to the mod page (e.g. on CurseForge):

Link to mod source/API:

**Comment by Cheaterpaul** [comment]
duplicate #65
