### ISSUE TITLE
Request compat for: Ripples of the Past 

### ISSUE THREAD

**Issue by JoJobanr1** [TeamLapen/VampirismIntegrations#97]
I would like to see integrations added for the mod mentioned in the title.  
it isn't available for the latest Minecraft version at the time of writing and is only for 1.16.5.

## About the mod
Link to the mod page (e.g. on CurseForge): https://www.curseforge.com/minecraft/mc-mods/ripples-of-the-past

Link to mod source/API: https://github.com/StandoByte/Ripples-of-the-Past

## What should be integrated exactly
In RoTP it adds a Stone Mask which gives the Vampirism spec, which should also add the Vampirism spec from the Vampirism Mod. The Vampirism that's added in RoTP gives some really cool abilities and I think there should be compatibility with blood sucking between the two Vampiric abilities so that it's synced up. (Example: If you use the abilities from RoTP it will drain blood from the blood bar in the Vampirism mod and vice versa) Compatibility should also be added with leveling up using the Vampirism spec from RoTP with the Vampirism mod. Also Included in RoTP mod is an ability called Hamon, which is the power of the sun and is the direct opposite of Vampirism and hurts/damages undead creatures and it would be cool to see Vampire Hunters use Hamon or have other Vampires be hurt and affected by Hamon. Blood bottles should refill the blood bar in RoTP. Holy Weapons, Water, Garlic and Crosses don't affect Vampires from JoJo, which is what the Vampirism is from in this mod, so if RoTP is installed and the user becomes a vampire from the stone mask these items don't affect them. Vampirism in RoTP also removes the hugger mechanic, so the blood bar that the Vampirism mod adds is gone too and would need to be added back. (I'm assuming it's a bug?) In the config of RoTP you can enable or disable if undead creatures are hostile or neutral to the player and I think the Vampirism mod should have the same thing in the config. because I think Skeletons and Zombies should naturally be hostile to the player. There is an effect added in the mod called "Sun Resistance" and could be used for Sunscreen and Umbrella compatibility, there's also an effect given when standing in the sun called "Sun Burn" which could also be added. There's one change that should definitely happen and that is RoTP gives the Vampirism spec extra hearts depending on the difficulty and with the added compatibility you could get those over time but should not get those right away. RoTP also adds a Vampiric Freezing ability but it doesn't really freeze players or mobs and it just slows them down so it would be great to add/fix compatibility that actually freezes entities. I hope this made since, if it didn't I can edit it and try to explain it better.

## I can help with
Editing textures and testing builds.

## Additional comments
The author of the RoTP mod has said they want to add integrations between RoTP and Vampirism, but since it's only one guy. (Don't know if that matters) It's going to take awhile to add that since he is working on adding other stuff to the mod currently.

**Comment by Cheaterpaul** [comment]
RIpples of the Past is not available past Minecraft 1.16

This issue can be reopened when the mod updates
