### ISSUE TITLE
Tough as nails compat not working 1.20.1

### ISSUE THREAD

**Issue by DemonJuice** [TeamLapen/VampirismIntegrations#99]
## Versions
- Minecraft:  1.20.1                 
- Forge:  47.2.17                      
- Vampirism: 1.20.1-1.9.3
- Integrations: 1.20.1-1.8.0-beta.1

## Issue Description
Thirst bar still shows and goes down over time requiring me to drink water

## Reproduce Steps
Add vampirism, tough as nails and vampirism integrations

Start new world

Use fangs to become a vampire

Once turned thirst bar will be visible and moving around will cause it to drain

## Additional Information

**Comment by Cheaterpaul** [comment]
What version of TAN do you use?

Is the `disableThirst` config option set to true?

**Comment by DemonJuice** [comment]
I'm using 1.20.1-9.0.0.96 and the config option is set to true

**Comment by Cheaterpaul** [comment]
The thirst should never go below 5 drops of water. We set to to 5 once it is below that.

Does your bar drain further?

**Comment by DemonJuice** [comment]
Sorry, I wasn't sure how the compatibility worked, I thought it either disabled the bar or kept it full completely but I can confirm it stays at 5 without draining further so it's working fine

**Comment by DemonJuice** [comment]
Sorry, I wasn't sure how the compatibility worked, I thought it either disabled the bar or kept it full completely but I can confirm it stays at 5 without draining further so it's working fine

**Comment by maxanier** [comment]
If you think it should better work differently, let us know.
The current solution is a trade-off between implementation effort, compatibility and function

**Comment by Cheaterpaul** [comment]
I disabled the rendering of the water bar. So it should no longer confuse players.
d6aa376e0995f890970dfacbf69d711b81691c75
